### ISSUE TITLE
Create Project Board

### ISSUE THREAD

**Issue by saidakf** [HYF-Class20/agile-development-groups1-all-about-trees#8]
# Create Project Board -- 10-project-board.md

Name: Agile Board
## Description

Create a project board for our team to track our progress and manage our tasks. The board will have columns for TODO, DOING, READY FOR REVIEW, NEEDS REVISION, and DONE. We will create labels for each must-have user story and for each type of task. We will also create issues for each task in our Development Strategy, including labels, milestones, and checklists.

## Tasks

- [ ] Create labels for each must-have user story and for each type of task
- [ ] Create issues for each task in our Development Strategy, including labels, milestones, and checklists
- [ ] Create project board with columns for TODO, DOING, READY FOR REVIEW, NEEDS REVISION, and DONE.
